plugins {
    id 'signing'
    id 'java-library'
    id 'checkstyle'
    id 'maven-publish'
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
}

group = 'io.github.emin0v'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withJavadocJar()
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    api 'org.springframework.boot:spring-boot-autoconfigure'

    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'com.h2database:h2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
    }
}

checkstyle {
    toolVersion = checkstyleVersion
    configFile = file('config/checkstyle/checkstyle.xml')
}

tasks.withType(Checkstyle).configureEach {
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}

tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'spring-boot-config-sentinel'
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }

            pom {
                name = 'Spring Boot Config Sentinel'
                description = 'Detect selected unsafe production configuration during Spring Boot startup.'
                url = 'https://github.com/Emin0v/spring-boot-config-sentinel'

                licenses {
                    license {
                        name = 'Apache License, Version 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                        distribution = 'repo'
                    }
                }
                developers {
                    developer {
                        id = 'Emin0v'
                        name = 'Mahammad Eminov'
                        url = 'https://github.com/Emin0v'
                    }
                }
                scm {
                    connection = 'scm:git:https://github.com/Emin0v/spring-boot-config-sentinel.git'
                    developerConnection = 'scm:git:ssh://git@github.com/Emin0v/spring-boot-config-sentinel.git'
                    url = 'https://github.com/Emin0v/spring-boot-config-sentinel'
                }
            }
        }
    }
}

signing {
    useGpgCmd()
    sign publishing.publications.mavenJava
}
